### ISSUE TITLE
Undeclared dependency 'bluebird'

### ISSUE THREAD

**Issue by silverwind** [iarna/promise-inflight#3]
This module fails to bundle in `rollup` because of it.

**Comment by bertho-zero** [comment]
Please fix this, `lerna` uses also it.

**Comment by vectronic** [comment]
Does anyone know the best way to workaround this when using rollup?

**Comment by bertho-zero** [comment]
With Yarn 2, in `.yarnrc.yml`:

```yml
packageExtensions:
  promise-inflight@^1.0.1:
    peerDependencies:
      bluebird: ^3.5.3
    peerDependenciesMeta:
      bluebird:
        optional: true
```
